### ISSUE TITLE
Cannot respond to messages

### ISSUE THREAD

**Issue by huzaifahj** [tywkeene/telnet-chat#2]
I'm seeing a bug where generally only 1 client can send messages. Logs such as this appear in the console:

```
2023/03/23 08:05:06 Failed to write message in room "General chat" to user "\xff\xfd\x03\xff\xfb\x18\xff\xfb\x1f\xff\xfb \xff\xfb!\xff\xfb\"\xff\xfb'\xff\xfd\x05\xff\xfb#hey" (127.0.0.1:60450): write tcp4 127.0.0.1:23->127.0.0.1:60450: use of closed network connection
```

**Comment by tywkeene** [comment]
Unfortunately, I don't have the time or interest in this project to chase bugs.

This project was a take home for an interview, so I did the best I could at the time. Maybe this is one of the bugs that caused me to not get that job lol.

Either way, I apologize but I can't commit to any assistance here.
